no_perms: "&cNo permission."

death:
  # Enables any death handling
  # Including messages, titles, etc..
  enabled: true
  # Disables sending messages
  disable_message: false
  message: "&a<winner> &7killed &c<looser>"
  # If death was not caused by another player (e.g. player died in void)
  # Placeholders: <player>
  message_no_player: "&c<player> &7died."
  # When player wins a bedwars or bridges game
  # Placeholders: <winner>, <loser>
  message_win: "&a<winner> &7won the game."
  # Sound that will be played after a player dies
  death_sound:
    # Enables playing sound after death
    enabled: true
    # Whether spectators should be able to hear death sound
    send_to_spectators: true
    sound: "ORB_PICKUP"
    volume: 1.0
    pitch: 1.0
  # Sound that will be played at the end of every game
  end_sound:
    # Enables playing sound after death
    enabled: true
    sound: "AMBIENCE_THUNDER"
    volume: 1.0
    pitch: 1.0
  # All values are in minecraft ticks!
  # 20 ticks = 1 IRL second
  # Placeholders: <winner>, <loser>
  win_title:
    # Enables winner title
    enabled: true
    title: "&a&lVICTORY"
    subtitle: "&a<winner> &fhas won the fight!"
    # How long should it take for the title to fade in
    fadeIn: 10
    # How long should the title stay visible
    stay: 20
    # How long should it take for the title to disappear
    fadeOut: 10
  lose_title:
    # Enables lose title
    enabled: true
    title: "&c&lDEFEAT"
    subtitle: "&a<winner> &fhas won the fight!"
    # How long should it take for the title to appear
    fadeIn: 10
    # How long should the title stay visible
    stay: 20
    # How long should it take for the title to disappear
    fadeOut: 10

# Message and title sent after the fight starts
start:
  # Enabled any start handling
  # Including message and title
  enabled: true
  # Disables sending message when a fight starts
  disable_message: false
  # Message when a fight starts (after the countdown)
  message:
    - " "
    - "&4&l[WARNING] &c&lDrag clicking or butterfly clicking might result in a ban!"
    - " "
  # All values are in minecraft ticks!
  # 20 ticks = 1 IRL second
  title:
    # Enables sending title after a fight starts
    enabled: false
    title: "&c&lFight"
    subtitle: "Match has started"
    # How long should it take for the title to appear
    fadeIn: 20
    # How long should the title stay visible
    stay: 20
    # How long should it take for the title to disappear
    fadeOut: 20