death_message:
  enabled: true
  format: "&a<winner> &7killed &c<looser>"

start_message:
  enabled: true
  format:
    - " "
    - "&4&l[WARNING] &c&lDrag clicking or butterfly clicking might result in a ban!"
    - " "