name: StrikeDeathMessages
version: 0.1.4
depend: [StrikePractice]
main: me.bermine.sdm.StrikeDeathMessages
author: Bermine
commands:
  sdm reload:
    aliases: [strikedeathmessage reload, strikedeathmessages reload]