name: StrikeDeathMessages
version: 0.1.5-HOTFIX
depend: [StrikePractice]
main: me.bermine.sdm.StrikeDeathMessages
author: Bermine
commands:
  sdm:
    aliases: [strikedeathmessage, strikedeathmessages]